# Generated by Django 5.2.17 on 2026-08-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("dashboard", "0001_initial"),)

    operations = (
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint", models.CharField(max_length=255, unique=True)),
                ("severity", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("occurrences", models.PositiveIntegerField(default=1)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_seen", models.DateTimeField(auto_now=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-last_seen",),
            },
        ),
    )
