# Generated by Django 5.2.17 on 2026-08-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("dashboard", "0002_alertevent"),)

    operations = (
        migrations.AddField(
            model_name="alertevent",
            name="acknowledged",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="alertevent",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    )
